FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY target/*.jar app.jar

RUN java -Djarmode=layertools -jar app.jar extract


FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /app/dependencies/ ./
COPY --from=builder /app/spring-boot-loader/ ./
COPY --from=builder /app/snapshot-dependencies/ ./
COPY --from=builder /app/application/ ./

ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]