apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: spring-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: kavindu20/discovery-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_INSTANCE_HOSTNAME
              value: discovery-server
            - name: MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT
              value: http://zipkin:9411/api/v2/spans
          readinessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: spring-micro
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761