apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: spring-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: kavindu20/inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: spring-micro
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8080
      targetPort: 8080