apiVersion: v1
kind: Secret
metadata:
  name: mysql-order-secret
  namespace: spring-micro
type: Opaque
stringData:
  password: "Kavindu@2000"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-inventory-secret
  namespace: spring-micro
type: Opaque
stringData:
  password: "Kavindu@2000"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-mysql-secret
  namespace: spring-micro
type: Opaque
stringData:
  root-password: "root"
  username: "keycloak"
  password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: spring-micro
type: Opaque
stringData:
  username: "admin"
  password: "1234"