spring.application.name=inventory-service
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/inventory_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Kavindu@2000

# Only in demo
spring.jpa.hibernate.ddl-auto=create-drop

# When set to zero, application runs on a random available port
server.port=0
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Zipkin endpoint
management.tracing.export.zipkin.endpoint=http://localhost:19411/api/v2/spans

# Sample 100% of requests
management.tracing.sampling.probability=1.0

# Show trace and span IDs in logs
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]