eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=9090
spring.application.name=api-gateway

# api-gateway configurations
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway = TRACE

# --------------------   Define Routes ----------------------

# product-service
spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/product/**

# order-service
spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/order/**

# discovery-service
spring.cloud.gateway.server.webmvc.routes[2].id=discovery-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8761
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/eureka/web
# Use filter because otherwise it just change port and use same url path
# Ex- localhost:9090/eureka/web -> localhost:8761/eureka/web
# But need  localhost:9090/eureka/web -> localhost:8761
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=SetPath=/

# Eureka static assets - Otherwise CSS and Icon are not appear
spring.cloud.gateway.server.webmvc.routes[3].id=discovery-assets
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8761
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/eureka/**

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/spring-boot-micro

# Zipkin endpoint
management.tracing.export.zipkin.endpoint=http://localhost:19411/api/v2/spans

# Sample 100% of requests
management.tracing.sampling.probability=1.0

# Show trace and span IDs in logs
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]