eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port=8761

# Zipkin endpoint
management.tracing.export.zipkin.endpoint=http://localhost:19411/api/v2/spans

# Sample 100% of requests
management.tracing.sampling.probability=1.0

# Show trace and span IDs in logs
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]