spring.application.name=product-service
spring.mongodb.uri=mongodb://localhost:27017/product-service-db
server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Zipkin endpoint
management.tracing.export.zipkin.endpoint=http://localhost:19411/api/v2/spans

# Sample 100% of requests
management.tracing.sampling.probability=1.0

# Show trace and span IDs in logs
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]